-- Magnitude:-

-- Find the total customers by countries.
SELECT
		country,
		COUNT(customer_id) AS Total_Customers 
FROM gold.dim_customers
GROUP BY country
ORDER BY Total_Customers DESC

-- Find the customers by gender
SELECT 
	gender,
	COUNT(customer_id) AS Total_Customers
FROM GOLD.dim_customers
GROUP BY gender
ORDER BY Total_Customers DESC

-- Find the total products by category
SELECT
	category,
	COUNT(product_id) Total_Products
FROM gold.dim_products
GROUP BY category
ORDER BY Total_Products DESC

-- What is the average costs in each category?
SELECT 
	category,
	AVG(cost) Total_Cost
FROM gold.dim_products
GROUP BY category
ORDER BY Total_Cost DESC

-- What is the total revenue generated for each category?
SELECT 
	p.category,
	SUM(f.sales_amount) AS Total_Revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY Total_Revenue DESC

-- What is the total revenue generated by each customers? (High Cardinality Dimension)
SELECT
	c.customer_key,
	c.first_name,
	c.last_name,
	SUM(f.sales_amount) AS Total_Revenue
FROM gold.fact_sales f
left join gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY c.customer_key,
		 c.first_name,
		 c.last_name
order by Total_Revenue DESC

-- What is the distribution of sold items across countries? (Low Cardinality Dimension)
SELECT
	c.country,
	SUM(f.quantity) AS Total_Quantity
FROM gold.fact_sales f
left join gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY c.country
order by Total_Quantity DESC
